name: Hola mundo

on: [push]

jobs:  
  hola:
    runs-on: ubuntu-latest
    
    steps:
    - name: Hola mundo
      run: echo 'Hola mundo'
    - name: Touch file
      run: touch hola.txt
    - name: Set text
      run: echo 'Hola archivo' >> hola.txt
    - name: Read file
      run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: LS
        run: ls -al
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - name: Check Node.js version
        run: node --version
